-- MySQL Script generated by MySQL Workbench
-- Thu May 10 12:49:00 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_deezer
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_deezer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_deezer` DEFAULT CHARACTER SET utf8 ;
USE `db_deezer` ;

-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_artistas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_artistas` (
  `codigo_artista` INT NOT NULL,
  `nombre_artista` VARCHAR(100) NULL,
  `url_imagen` VARCHAR(500) NULL,
  PRIMARY KEY (`codigo_artista`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_genero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_genero` (
  `codigo_genero` INT NOT NULL,
  `nombre_genero` VARCHAR(100) NULL,
  PRIMARY KEY (`codigo_genero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_albumes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_albumes` (
  `codigo_album` INT NOT NULL,
  `codigo_artista` INT NOT NULL,
  `codigo_genero` INT NOT NULL,
  `nombre_album` VARCHAR(100) NULL,
  `url_imagen` VARCHAR(500) NULL,
  `duracion` INT NULL,
  PRIMARY KEY (`codigo_album`),
  INDEX `fk_tbl_albumes_tbl_artistas_idx` (`codigo_artista` ASC),
  INDEX `fk_tbl_albumes_tbl_genero1_idx` (`codigo_genero` ASC),
  CONSTRAINT `fk_tbl_albumes_tbl_artistas`
    FOREIGN KEY (`codigo_artista`)
    REFERENCES `db_deezer`.`tbl_artistas` (`codigo_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_albumes_tbl_genero1`
    FOREIGN KEY (`codigo_genero`)
    REFERENCES `db_deezer`.`tbl_genero` (`codigo_genero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_canciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_canciones` (
  `codigo_cancion` INT NOT NULL,
  `codigo_album` INT NOT NULL,
  `codigo_artista` INT NOT NULL,
  `nombre_cancion` VARCHAR(100) NULL,
  `url_cancion` VARCHAR(500) NULL,
  PRIMARY KEY (`codigo_cancion`),
  INDEX `fk_tbl_canciones_tbl_albumes1_idx` (`codigo_album` ASC),
  INDEX `fk_tbl_canciones_tbl_artistas1_idx` (`codigo_artista` ASC),
  CONSTRAINT `fk_tbl_canciones_tbl_albumes1`
    FOREIGN KEY (`codigo_album`)
    REFERENCES `db_deezer`.`tbl_albumes` (`codigo_album`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_canciones_tbl_artistas1`
    FOREIGN KEY (`codigo_artista`)
    REFERENCES `db_deezer`.`tbl_artistas` (`codigo_artista`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_tipos_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_tipos_usuarios` (
  `codigo_tipo_usuario` INT NOT NULL,
  `tipo_usuario` VARCHAR(45) NULL,
  PRIMARY KEY (`codigo_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_usuarios` (
  `codigo_usuario` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(100) NOT NULL,
  `nombre_usuario` VARCHAR(100) NULL,
  `apellido` VARCHAR(100) NULL,
  `sexo` VARCHAR(45) NULL,
  `fecha` DATE NULL,
  `direccion` VARCHAR(500) NULL,
  `codigopostal` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `url_imagen_perfil` VARCHAR(100) NULL,
  `codigo_tipo_usuario` INT NOT NULL,
  PRIMARY KEY (`codigo_usuario`),
  INDEX `fk_tbl_usuarios_tbl_tipos_usuarios1_idx` (`codigo_tipo_usuario` ASC),
  CONSTRAINT `fk_tbl_usuarios_tbl_tipos_usuarios1`
    FOREIGN KEY (`codigo_tipo_usuario`)
    REFERENCES `db_deezer`.`tbl_tipos_usuarios` (`codigo_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deezer`.`tbl_favoritas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deezer`.`tbl_favoritas` (
  `codigo_favoritas` INT NOT NULL,
  `codigo_usuario` INT NOT NULL,
  `codigo_cancion` INT NOT NULL,
  PRIMARY KEY (`codigo_favoritas`),
  INDEX `fk_tbl_favoritas_tbl_usuarios1_idx` (`codigo_usuario` ASC),
  INDEX `fk_tbl_favoritas_tbl_canciones1_idx` (`codigo_cancion` ASC),
  CONSTRAINT `fk_tbl_favoritas_tbl_usuarios1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `db_deezer`.`tbl_usuarios` (`codigo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_favoritas_tbl_canciones1`
    FOREIGN KEY (`codigo_cancion`)
    REFERENCES `db_deezer`.`tbl_canciones` (`codigo_cancion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
